@startuml
!theme materia-outline

left to right direction

skinparam class {
    BackgroundColor white
    BorderColor #214D7B
}

skinparam ArrowColor #233950
skinparam DefaultTextAlignment center
skinparam shadowing false
skinparam ArrowThickness 2

class Bitmap {
    - data: u32
    --
    + new() : Bitmap
    + set(index: usize) : void
    + clear(index: usize) : void
    + get(index: usize) : bool
    + find_first_unset() : Option<usize>
}

class IrqAllocator {
    - bitmap: Bitmap
    --
    + new() : IrqAllocator
    + alloc() : Option<usize>
    + free(index: usize) : void
}

IrqAllocator --> Bitmap : uses
@enduml